// <auto-generated />
using AutoCenter.Web.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoCenter.Web.Migrations
{
    [DbContext(typeof(AutoCenterDbContext))]
    [Migration("20250820220146_SeedListing")]
    partial class SeedListing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("AutoCenter.Web.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Description = "A sleek and stylish coupe",
                            IsActive = true,
                            Price = 12000m,
                            Title = "BMW 320i Coupe"
                        });
                });

            modelBuilder.Entity("AutoCenter.Web.Models.Listing", b =>
                {
                    b.OwnsOne("AutoCenter.Web.Models.VehicleSpecsSpecs", "VehicleSpecs", b1 =>
                        {
                            b1.Property<int>("ListingId")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("BodyType")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("Color")
                                .HasColumnType("INTEGER");

                            b1.Property<int?>("FuelType")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Make")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Mileage")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("Transmission")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Vin")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Year")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ListingId");

                            b1.ToTable("Listings");

                            b1.WithOwner()
                                .HasForeignKey("ListingId");

                            b1.HasData(
                                new
                                {
                                    ListingId = 2,
                                    BodyType = 3,
                                    Color = 1,
                                    FuelType = 0,
                                    Make = "BMW",
                                    Mileage = "150000",
                                    Model = "320i",
                                    Transmission = 1,
                                    Vin = "WBAVC31050KT12345",
                                    Year = "2013"
                                });
                        });

                    b.Navigation("VehicleSpecs")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
